# Generated by Django 2.2.2 on 2019-08-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrative',
            options={'verbose_name': '专业科名称', 'verbose_name_plural': '专业科名称'},
        ),
        migrations.AlterField(
            model_name='administrative',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='administrative',
            name='name',
            field=models.CharField(max_length=20, verbose_name='专业科名称'),
        ),
    ]
