# Generated by Django 2.2.2 on 2019-10-10 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_auto_20190808_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherdevelopment',
            options={'verbose_name': '教研室', 'verbose_name_plural': '教研室'},
        ),
        migrations.AlterField(
            model_name='teacherdevelopment',
            name='administrative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administrative.Administrative', verbose_name='教研室'),
        ),
        migrations.AlterField(
            model_name='teacherdevelopment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='teacherdevelopment',
            name='name',
            field=models.CharField(max_length=20, verbose_name='教研室名称'),
        ),
    ]
