# Generated by Django 2.2 on 2019-06-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190617_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('teacher__username',), 'verbose_name': '教师信息', 'verbose_name_plural': '教师信息'},
        ),
    ]
