# Generated by Django 2.2.2 on 2019-06-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20190619_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('belong_to', '-teacher__username'), 'verbose_name': '教师信息', 'verbose_name_plural': '教师信息'},
        ),
    ]
