# Generated by Django 2.2.2 on 2019-06-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20190624_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('belong_to', 'teacher__username'), 'verbose_name': '教师信息', 'verbose_name_plural': '教师信息'},
        ),
    ]
