# Generated by Django 2.2.2 on 2019-08-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('name', 'major')},
        ),
    ]
