# Generated by Django 2.2.2 on 2019-09-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_headteacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadTeacher',
        ),
    ]
