# Generated by Django 2.2 on 2019-06-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='belong_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administrative.TeacherDevelopment'),
        ),
    ]
