# Generated by Django 2.2.2 on 2019-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='content',
            field=models.CharField(max_length=20, verbose_name='简介'),
        ),
    ]
