# Generated by Django 2.2.2 on 2019-09-10 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_photo'),
        ('teachingtask', '0008_teachingtask_is_changed'),
        ('student', '0002_student_nick_name'),
        ('tevaluation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evalution_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=1)),
                ('evalution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tevaluation.Tevaluation')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachingtask.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
            options={
                'unique_together': {('evalution', 'student', 'teacher', 'semester')},
            },
        ),
    ]
