# Generated by Django 2.2.2 on 2019-09-11 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_belong_to'),
        ('tevaluation', '0002_evalution_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='evalution_score',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course'),
        ),
    ]
