# Generated by Django 2.2.2 on 2019-09-11 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_photo'),
        ('student', '0002_student_nick_name'),
        ('course', '0002_course_belong_to'),
        ('teachingtask', '0008_teachingtask_is_changed'),
        ('tevaluation', '0003_evalution_score_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evalution_score',
            unique_together={('evalution', 'student', 'teacher', 'semester', 'course')},
        ),
    ]
