# Generated by Django 2.2.2 on 2019-10-10 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0003_auto_20190924_1210'),
        ('course', '0002_course_belong_to'),
        ('teacher', '0006_teacher_photo'),
        ('teachingtask', '0008_teachingtask_is_changed'),
        ('tevaluation', '0004_auto_20190911_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='tevaluation.Comment')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to=settings.AUTH_USER_MODEL)),
                ('root', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='tevaluation.Comment')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachingtask.Semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
            options={
                'ordering': ['-comment_time'],
            },
        ),
    ]
