# Generated by Django 2.2.2 on 2019-10-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tevaluation', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevaluation',
            name='content',
            field=models.CharField(max_length=200, verbose_name='简介'),
        ),
    ]
