# Generated by Django 2.2.2 on 2019-10-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tevaluation', '0006_auto_20191014_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='tevaluation',
            name='weights',
            field=models.FloatField(default=0, verbose_name='权重'),
        ),
    ]
