# Generated by Django 2.2.2 on 2019-06-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_middle_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Middle_Score',
        ),
    ]
