# Generated by Django 2.2.2 on 2019-06-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_nick_name'),
        ('teachingtask', '0007_remove_teachingtask_level'),
        ('score', '0004_delete_middle_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('task', 'student', 'make_up')},
        ),
        migrations.RemoveField(
            model_name='score',
            name='root',
        ),
    ]
