# Generated by Django 2.2.2 on 2019-06-24 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_auto_20190624_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_comment', to='score.Score'),
        ),
    ]
