# Generated by Django 2.2.2 on 2019-06-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0007_auto_20190624_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rootscore', to='score.Score'),
        ),
    ]
