# Generated by Django 2.2.2 on 2019-06-24 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20190624_1807'),
        ('score', '0008_auto_20190624_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_input_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='score_input_teachers', to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='score',
            name='make_up_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='make_up_teacher', to='teacher.Teacher'),
        ),
    ]
