# Generated by Django 2.2.2 on 2019-07-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingtask', '0007_remove_teachingtask_level'),
        ('score', '0010_auto_20190625_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='execute_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='execute_semester', to='teachingtask.Semester'),
        ),
        migrations.AddField(
            model_name='score',
            name='is_execute',
            field=models.BooleanField(default=False),
        ),
    ]
