# Generated by Django 2.2.2 on 2019-10-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0012_auto_20191010_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
