# Generated by Django 2.2.2 on 2019-11-11 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_sell', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'ordering': ('create_time', 'is_sell'),
            },
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auction.Product')),
            ],
            options={
                'verbose_name': '产品价格',
                'verbose_name_plural': '产品价格',
                'ordering': ('price', 'create_time'),
                'unique_together': {('product', 'belong', 'price')},
            },
        ),
    ]
