# Generated by Django 2.2.2 on 2019-11-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='product',
            name='start_price',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
