# Generated by Django 2.2.2 on 2019-11-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20191118_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
