# Generated by Django 2.2.2 on 2019-06-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_auto_20190619_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBaseWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('weights', models.FloatField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
            options={
                'ordering': ['teacher', 'name'],
                'unique_together': {('teacher', 'name')},
            },
        ),
    ]
