# Generated by Django 2.2 on 2019-06-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_year', models.CharField(max_length=20)),
                ('semester_period', models.CharField(max_length=5)),
                ('is_execute', models.BooleanField(default=False)),
                ('start_time', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
            ],
            options={
                'ordering': ('semester_year', 'semester_period'),
            },
        ),
        migrations.CreateModel(
            name='TeachingTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_input', models.BooleanField(default=False)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.Classes')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachingtask.Semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
            options={
                'verbose_name': '教学任务',
                'verbose_name_plural': '教学任务',
                'ordering': ('teacher__teacher__username',),
                'unique_together': {('semester', 'teacher', 'course', 'classes')},
            },
        ),
    ]
