# Generated by Django 2.2 on 2019-06-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('classes', '0001_initial'),
        ('teachingtask', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingtask',
            unique_together={('semester', 'course', 'classes')},
        ),
    ]
