# Generated by Django 2.2 on 2019-06-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachingtask', '0002_auto_20190617_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingtask',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher'),
        ),
    ]
