# Generated by Django 2.2.2 on 2019-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_register', '0003_skillchoose'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillproject',
            name='game_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skillproject',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillproject',
            name='context',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
