# Generated by Django 2.2.2 on 2019-09-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_num',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
