# Generated by Django 2.2.2 on 2019-07-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_course_belong_to'),
        ('teachingtask', '0007_remove_teachingtask_level'),
        ('teacher', '0005_auto_20190624_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeUpTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_up', models.IntegerField(default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.Course')),
                ('execute_semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='makeup_execute_semester', to='teachingtask.Semester')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_semester', to='teachingtask.Semester')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.Teacher')),
            ],
            options={
                'ordering': ['create_time'],
                'unique_together': {('course', 'semester', 'execute_semester', 'teacher', 'make_up')},
            },
        ),
    ]
