# Generated by Django 2.2.2 on 2019-07-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_nick_name'),
        ('make_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuptask',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student'),
        ),
    ]
