# Generated by Django 2.2.2 on 2019-07-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_nick_name'),
        ('teacher', '0005_auto_20190624_1807'),
        ('course', '0002_course_belong_to'),
        ('teachingtask', '0007_remove_teachingtask_level'),
        ('make_up', '0002_makeuptask_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='makeuptask',
            unique_together={('course', 'semester', 'execute_semester', 'teacher', 'make_up', 'student')},
        ),
    ]
