# Generated by Django 2.2.2 on 2019-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_up', '0003_auto_20190706_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuptask',
            name='is_input',
            field=models.BooleanField(default=False),
        ),
    ]
