# Generated by Django 2.2.2 on 2019-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_up', '0004_makeuptask_is_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeuptask',
            name='make_up',
            field=models.IntegerField(default=2),
        ),
    ]
