# Generated by Django 2.2 on 2019-06-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachingtask', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('attendance_time', models.DateField()),
                ('attendance_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_change', to='attendance.AttendanceReason')),
                ('attendance_reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attendance.AttendanceReason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='student.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teachingtask.TeachingTask')),
            ],
            options={
                'unique_together': {('task', 'student', 'attendance_time')},
            },
        ),
    ]
